server {
    listen 80;
    server_name 172.16.30.179;
    root /var/www/html/public;


    index index.php index.html index.htm;

    error_log  /var/log/nginx/laravel-ansible-error.log;
    access_log /var/log/nginx/laravel-ansible-access.log;
    
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi.conf;
        # Here, laravel_app is supposed to be the hostname of docekr container. Thus,
        # docker contaienr's service must be named laravel_app in docker-compose.yml
        # fastcgi_pass laravel_app:9000;

        #testing the nginx in default environment
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}